import type { Metadata } from "next";
import "./globals.scss";
import PageLoader from "@/components/Common/Loaders/PageLoader";
import { PageLoaderProvider } from "@/context/PageLoaderContext/Provider";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "LendSqr App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
      <PageLoaderProvider> 
       <Suspense fallback={<div>Loading...</div>}>
        {children}
        </Suspense>
        <PageLoader/>
       </PageLoaderProvider> 
      </body>
    </html>
  );
}
