import type { Metadata } from "next";
import "./globals.scss";
import PageLoader from "@/components/Common/Loaders/PageLoader";
import { PageLoaderProvider } from "@/context/PageLoaderContext/Provider";

export const metadata: Metadata = {
  title: "LendSqr App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
      <PageLoaderProvider> 
        {children}
        <PageLoader/>
       </PageLoaderProvider> 
      </body>
    </html>
  );
}
